### ISSUE TITLE
Failed to activate the nyancat package

### ISSUE THREAD

**Issue by yh392261226** [dz/atom-nyancat#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [nyancat](https://github.com/dz/atom-nyancat) package, v0.2.0
### Stack Trace

Failed to activate the nyancat package

```
At Cannot read property '1' of null

TypeError: Cannot read property '1' of null
    at Object.module.exports.AtomNyancat.update (/Users/json/.atom/packages/nyancat/lib/atom-nyancat.coffee:61:53)
    at Object.module.exports.AtomNyancat.subActive (/Users/json/.atom/packages/nyancat/lib/atom-nyancat.coffee:48:19)
    at /Users/json/.atom/packages/nyancat/lib/atom-nyancat.coffee:19:17
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:145:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:304:33)
    at Object.module.exports.AtomNyancat.activate (/Users/json/.atom/packages/nyancat/lib/atom-nyancat.coffee:16:43)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-monokai"
    ],
    "projectHome": "/Users/json/data/app/www/"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.12.1
autocomplete-go, v0.1.1
autocomplete-php, v0.3.7
emmet, v2.3.17
emmet-simplified, v2.5.0
environment, v1.1.1
git-go, v1.0.1
git-tab-status, v1.9.2
go-config, v0.3.1
highlight-column, v0.5.0
javascript-snippets, v1.0.0
linter, v1.11.3
node-debugger, v1.3.2
node-on-fire, v0.1.0
nodejs-snippets, v1.1.0
nyancat, v0.2.0
seti-monokai, v0.3.1
seti-ui, v0.8.1
shadow, v0.1.0

# Dev
No dev packages
```

**Comment by bgura** [comment]
I saw another atom plugin had a similar issue. I wonder if their fix can be applied here? Restarting atom fixed the issue for me after installing the plugin

If you go to the atom-pigments issues 92 i think they had a related issue.

**Comment by msollami** [comment]
This still happens when I launch Atom now

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.10.5
**Thrown From**: [nyancat](https://github.com/dz/atom-nyancat) package, v0.2.0

### Stack Trace

Failed to activate the nyancat package

```
At Cannot read property '1' of null

TypeError: Cannot read property '1' of null
    at Object.module.exports.AtomNyancat.update (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:49:52)
    at Object.module.exports.AtomNyancat.subActive (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:38:6)
    at /Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:17:8
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:145:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:324:33)
    at Object.module.exports.AtomNyancat.activate (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:15:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "tabs",
      "dev-live-reload",
      "live-doc-viewer",
      "scrolly",
      "livereload",
      "linter",
      "linter-python-pep8",
      "linter-python-pyflakes",
      "python-autopep8",
      "python-iresolve",
      "python-isort",
      "python-tools",
      "language-python"
    ],
    "themes": [
      "atom-dark-ui",
      "Chromodynamics"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Chromodynamics, v0.0.7
MagicPython, v0.5.9
goto-mathematica, v0.3.0
language-dotfiles, v0.2.0
linter-flake8, v1.13.0
linter-pylint, v1.2.0
markdown-preview-plus, vundefined
markdown-scroll-sync, vundefined
minimap, v4.21.0
nyancat, v0.2.0
python-indent, v0.4.3
simple-copy-path, v1.0.0
terminal-plus, v0.14.5
tree-view-finder, v0.2.1
tree-view-open-files, v0.3.0

# Dev
No dev packages
```
