### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by msollami** [dz/atom-nyancat#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [nyancat](https://github.com/dz/atom-nyancat) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:49

TypeError: Cannot read property '1' of null
    at Object.module.exports.AtomNyancat.update (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:49:52)
    at /Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:37:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:113:47
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:909:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.restoreScrollTopIfNeeded (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1740:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setLineHeight (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1230:14)
    at LinesComponent.module.exports.LinesComponent.measureLineHeightAndDefaultCharWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-component.js:136:22)
    at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1044:36)
    at TextEditorComponent.module.exports.TextEditorComponent.sampleFontStyling (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1025:14)
    at TextEditorComponent.sampleFontStyling (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:272:12)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:975:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:95:22)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:327:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:506:18
```
### Commands

```
     -0:31.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.3.0 markdown-preview:preview-file (span.name.icon.icon-book)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "tabs",
      "dev-live-reload",
      "live-doc-viewer",
      "scrolly",
      "livereload",
      "linter",
      "linter-python-pep8",
      "linter-python-pyflakes",
      "python-autopep8",
      "python-iresolve",
      "python-isort",
      "python-tools",
      "language-python"
    ],
    "themes": [
      "atom-dark-ui",
      "Chromodynamics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Chromodynamics, v0.0.7
MagicPython, v0.5.8
goto-mathematica, v0.1.0
linter-flake8, v1.12.1
linter-pylint, v1.2.0
markdown-preview-plus, vundefined
markdown-scroll-sync, vundefined
minimap, v4.19.0
nyancat, v0.2.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by msollami** [comment]
Still broken:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.10.5
**Thrown From**: [nyancat](https://github.com/dz/atom-nyancat) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:49

TypeError: Cannot read property '1' of null
    at Object.module.exports.AtomNyancat.update (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:49:52)
    at Object.module.exports.AtomNyancat.subActive (/Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:38:6)
    at /Users/mike/.atom/packages/nyancat/lib/atom-nyancat.coffee:17:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:255:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:319:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:21)
    at atom-workspace.commandRegistry.add.pane:show-previous-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:14:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "dev-live-reload",
      "live-doc-viewer",
      "scrolly",
      "livereload",
      "linter",
      "linter-python-pep8",
      "linter-python-pyflakes",
      "python-autopep8",
      "python-iresolve",
      "python-isort",
      "python-tools",
      "language-python"
    ],
    "themes": [
      "atom-dark-ui",
      "Chromodynamics"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Chromodynamics, v0.0.7
MagicPython, v0.5.9
color-tabs, v0.1.8
goto-mathematica, v0.3.0
language-dotfiles, v0.2.0
linter-clojure, v1.1.2
linter-flake8, v1.13.0
linter-pylint, v1.2.0
markdown-preview-plus, vundefined
markdown-scroll-sync, vundefined
minimap, v4.21.0
nyancat, v0.2.0
python-indent, v0.4.3
simple-copy-path, v1.0.0
terminal-plus, v0.14.5
tree-view-finder, v0.2.1
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by msollami** [comment]
This happens when I open a new file or switch tabs to an empty/unsaved file. Any suggestions?
